gems:
  - jekyll-seo-tag
  - jekyll-sitemap
title: DashTek - 上海达世科技有限公司
description: 上海达世科技有限公司世界领先的区块链相关设备研发、设计、生产及服务商
url: http://dashtek.io
author: DASHTEK CO., LTD.
logo: /images/logo.png
google_site_verification: OpbrCFSKUkkJhpreRekY4xMpeHjVZwNzR5CSbyarP8Y
